#配置数据源的属性
spring:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/,classpath:/static/resources/layui
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/rpms?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      enable: true
   #监控配置
      stat-view-servlet:
        enabled: false
        login-username: root
        login-password: 123456
        url-pattern: /druid/*
  #thymeleaf的配置 
  thymeleaf: 
    cache: false
    enabled: true
#      web-stat-filter: 
#        enabled: true
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#配置mybatisplus
mybatis-plus:
  mapper-locations:
  - classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


